---
apiVersion: v2
name: where-to-eat-metachart
version: "0.0.1"

dependencies:
  - name: "rabbitmq"
    version: "12.4.2"
    repository: "https://charts.bitnami.com/bitnami"
    alias: "rabbitmq"

  - name: "qdrant"
    version: "0.6.1"
    repository: "https://qdrant.github.io/qdrant-helm"
    alias: "qdrant"
